### PR TITLE
Update wrapper version

### PR DESCRIPTION
**Pull request by daniel-butler-irl**
### Description

updating wrapper and tests

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by daniel-butler-irl — COMMENTED** [review]
/run pipeline

**Comment by daniel-butler-irl** [comment]
bug in the wrapper fixed: https://github.com/terraform-ibm-modules/ibmcloud-terratest-wrapper/pull/878

**Comment by daniel-butler-irl** [comment]
Bug in the wrapper causes this test to pass on failure. working on fix, do not merge

**Comment by daniel-butler-irl** [comment]
closing letting renovate update

**Comment by ocofaigh** [comment]
@daniel-butler-irl If the test wrapper config is ok here, and pipeline is only failing due to backend issue, lets proceed with a force merge here. I kind of want the updater wrapper to run in https://github.com/terraform-ibm-modules/stack-retrieval-augmented-generation/pull/208

**Review by ocofaigh — APPROVED** [review]

**Comment by daniel-butler-irl** [comment]
@daniel-butler-irl Not sure if you want to force merge, all deploys are successful it just failed on undeploy. Looks like its KMS still has key inside it and fails instance delete. Presumably this is an issue in the main branch too...
>  "Result": {
│         "details": "{\"status_code\":409,\"name\":\"ConflictError\",\"message\":{\"message\":\"CONTAINS_ACTIVE_KEYS: Remove all keys before de-provisioning: Instance contains 2 active keys\",\"name\":\"ConflictError\",\"status_code\":409,\"transaction_id\":\"\"},\"description\":\"CONTAINS_ACTIVE_KEYS: Remove all keys before de-provisioning: Instance contains 2 active keys\"}",
│         "error_code": "RC-ServiceBrokerErrorResponse",
│         "message": "Please contact the Service Provider for this error. [409, Conflict] CONTAINS_ACTIVE_KEYS: Remove all keys before de-provisioning: Instance contains 2 active keys",
│         "status_code": 422,
│         "transaction_id": "626c-8f564977efde97e1"
│     },

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
