### PR TITLE
Python Stack Deploy script

### PR DESCRIPTION
**Pull request by daniel-butler-irl**
### Description
Python implementation of the deploy script for easier maintenance
Resolves issues:
https://github.com/terraform-ibm-modules/stack-retrieval-augmented-generation/issues/46
https://github.com/terraform-ibm-modules/stack-retrieval-augmented-generation/issues/60
https://github.com/terraform-ibm-modules/stack-retrieval-augmented-generation/issues/74
Undeploy also supported 
Disabling tests for now since they are being skipped anyway

Stack definition update is not working for me manually or via the script. I don;t think its a bug with the script.
Manual command
> `ibmcloud project config-update --project-id 12234 --id 56789 --definition @stack_definition.json`

Response:
>FAILED
Error parsing flag 'definition' as 'model ProjectConfigDefinitionPatch':
error unmarshalling projectv1.ProjectConfigDefinitionPatchIntf: error unmarshalling property 'inputs': json: cannot unmarshal array into Go value of type map[string]interface {}

**_UPDATE:_** This is a known limitation the stack definition cannot be used to update the stack at this time...

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by daniel-butler-irl** [comment]
@vburckhardt for now I just appended the documentation to the bottom of the readme, I left the docs for the shell script in place

**Review by vburckhardt — APPROVED** [review]

**Pull request merged**
