### PR TITLE
feat: Bump dependencies

### PR DESCRIPTION
**Pull request by vburckhardt**
### Description

INFO:root:Updating 1 - Account Infrastructure Base
INFO:root:current version: v1.7.0
INFO:root:latest version: v1.10.2
INFO:root:latest version locator: 7a4d68b4-cf8b-40cd-a3d1-f49aff526eb3.5e2f1f48-776d-4dce-87f5-de2940fdc2e3-global
INFO:root:Updating 1 - Account Infrastructure Base to version v1.10.2

INFO:root:Updating 2a - Security Service - Key Management
INFO:root:current version: v4.13.0
INFO:root:latest version: v4.14.0
INFO:root:latest version locator: 7a4d68b4-cf8b-40cd-a3d1-f49aff526eb3.4a3affda-ffc6-4d14-a4f7-aeeb2b80908c-global
INFO:root:Updating 2a - Security Service - Key Management to version v4.14.0

INFO:root:Updating 2b - Security Service - Secret Manager
INFO:root:current version: v1.13.1
INFO:root:latest version: v1.15.0
INFO:root:latest version locator: 7a4d68b4-cf8b-40cd-a3d1-f49aff526eb3.62deff73-587f-4dc6-99cf-15854a2d9ba0-global
INFO:root:Updating 2b - Security Service - Secret Manager to version v1.15.0

INFO:root:Updating 2c - Security Service - Security Compliance Center
INFO:root:current version: v1.6.5
INFO:root:latest version: v1.12.1
INFO:root:latest version locator: 7a4d68b4-cf8b-40cd-a3d1-f49aff526eb3.f4dfbf7a-5bc6-4fc7-bfe8-e9bfb3dc145e-global
INFO:root:Updating 2c - Security Service - Security Compliance Center to version v1.12.1

INFO:root:Updating 3 - Observability - Logging Monitoring Activity Tracker
INFO:root:current version: v1.4.0
INFO:root:latest version: v1.9.1
INFO:root:latest version locator: 7a4d68b4-cf8b-40cd-a3d1-f49aff526eb3.2df9138c-f658-4d5a-b212-8c1445a5e6c8-global
INFO:root:Updating 3 - Observability - Logging Monitoring Activity Tracker to version v1.9.1

INFO:root:Updating 4 - WatsonX SaaS services
INFO:root:current version: v1.0.0
INFO:root:latest version: v1.3.2
INFO:root:latest version locator: 7a4d68b4-cf8b-40cd-a3d1-f49aff526eb3.0645267d-b8e9-42d9-8b4f-ea67dc713ff7-global
INFO:root:Updating 4 - WatsonX SaaS services to version v1.3.2

INFO:root:Updating 5 - Sample RAG app - Application Lifecycle Management
INFO:root:current version: 1.2.1
INFO:root:latest version: 1.8.0
INFO:root:latest version locator: 1082e7d2-5e2f-0a11-a3bc-f88a8e1931fc.cce4d1b1-c09a-4c23-8aba-92f6e9f38cda-global
INFO:root:Updating 5 - Sample RAG app - Application Lifecycle Management to version 1.8.0

INFO:root:Updating 6 - Sample RAG app configuration
INFO:root:current version: v1.9.1
INFO:root:latest version: v2.0.1
INFO:root:latest version locator: 7a4d68b4-cf8b-40cd-a3d1-f49aff526eb3.af19228a-3182-46da-b52a-b1d9f662609d-global
INFO:root:Updating 6 - Sample RAG app configuration to version v2.0.1

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by daniel-butler-irl — APPROVED** [review]

**Comment by vburckhardt** [comment]
INFO:root:Updating 1 - Account Infrastructure Base
INFO:root:current version: v1.10.2
INFO:root:latest version: v1.10.4
INFO:root:latest version locator: 7a4d68b4-cf8b-40cd-a3d1-f49aff526eb3.be107739-fdfc-4089-95e0-def4abac847d-global
INFO:root:Updating 1 - Account Infrastructure Base to version v1.10.4

INFO:root:Updating 2a - Security Service - Key Management
INFO:root:current version: v4.14.0
INFO:root:latest version: v4.14.0
INFO:root:latest version locator: 7a4d68b4-cf8b-40cd-a3d1-f49aff526eb3.4a3affda-ffc6-4d14-a4f7-aeeb2b80908c-global
INFO:root:2a - Security Service - Key Management is already up to date. No updates were made.

INFO:root:Updating 2b - Security Service - Secret Manager
INFO:root:current version: v1.15.0
INFO:root:latest version: v1.15.1
INFO:root:latest version locator: 7a4d68b4-cf8b-40cd-a3d1-f49aff526eb3.037f40f0-2575-40fe-a771-81ac437d5d60-global
INFO:root:Updating 2b - Security Service - Secret Manager to version v1.15.1

INFO:root:Updating 2c - Security Service - Security Compliance Center
INFO:root:current version: v1.12.1
INFO:root:latest version: v1.12.2
INFO:root:latest version locator: 7a4d68b4-cf8b-40cd-a3d1-f49aff526eb3.f91391b9-72c3-48c2-b40d-fb27cfc7d00c-global
INFO:root:Updating 2c - Security Service - Security Compliance Center to version v1.12.2

INFO:root:Updating 3 - Observability - Logging Monitoring Activity Tracker
INFO:root:current version: v1.9.1
INFO:root:latest version: v1.9.2
INFO:root:latest version locator: 7a4d68b4-cf8b-40cd-a3d1-f49aff526eb3.351cb33e-7037-4016-a38f-4e10c4a7ef68-global
INFO:root:Updating 3 - Observability - Logging Monitoring Activity Tracker to version v1.9.2

INFO:root:Updating 4 - WatsonX SaaS services
INFO:root:current version: v1.3.2
INFO:root:latest version: v1.3.4
INFO:root:latest version locator: 1082e7d2-5e2f-0a11-a3bc-f88a8e1931fc.c237751c-d3dd-4c23-b0b1-ba726d30c8e9-global
INFO:root:Updating 4 - WatsonX SaaS services to version v1.3.4

INFO:root:Updating 5 - Sample RAG app - Application Lifecycle Management
INFO:root:current version: 1.8.0
INFO:root:latest version: 1.8.0
INFO:root:latest version locator: 1082e7d2-5e2f-0a11-a3bc-f88a8e1931fc.cce4d1b1-c09a-4c23-8aba-92f6e9f38cda-global
INFO:root:5 - Sample RAG app - Application Lifecycle Management is already up to date. No updates were made.

INFO:root:Updating 6 - Sample RAG app configuration
INFO:root:current version: v2.0.1
INFO:root:latest version: v2.0.1
INFO:root:latest version locator: 7a4d68b4-cf8b-40cd-a3d1-f49aff526eb3.af19228a-3182-46da-b52a-b1d9f662609d-global
INFO:root:6 - Sample RAG app configuration is already up to date. No updates were made.

**Comment by vburckhardt** [comment]
Tested manual deployment, which is working

**Comment by ocofaigh** [comment]
Tests should be unblocked again now that https://github.com/terraform-ibm-modules/stack-retrieval-augmented-generation/pull/144 is merged

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
